# Generated by Django 2.1 on 2018-08-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
